version: '3'

services:
  db:
    image: postgres:16
    #env_file:
    #  - .env
    #environment:
    #  POSTGRES_DB: ${DB_NAME}
    #  POSTGRES_USER: ${DB_USER}
    #  POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - milanet
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    #environment:
    #  DB_NAME: ${DB_NAME}
    #  DB_USER: ${DB_USER}
    #  DB_PASSWORD: ${DB_PASSWORD}
    #  DB_HOST: db
    #volumes:
    #  - ./milatiendard/settings_prod.py:/app/settings.py
    networks:
      - milanet

networks:
  milanet:

