# Generated by Django 5.0.4 on 2024-05-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opiniones',
            old_name='rating',
            new_name='calificacion',
        ),
        migrations.RenameField(
            model_name='opiniones',
            old_name='comentario',
            new_name='opinion',
        ),
    ]
