# Generated by Django 5.0.4 on 2024-05-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_rename_rating_opiniones_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opiniones',
            table='opiniones',
        ),
    ]
